AppointmentBookingSystem/AppointmentBookingSystem.Web/Controllers/BookingController.cs
using AppointmentBookingSystem.Application.Common.Contract;
using AppointmentBookingSystem.Application.Common.Utility;
using AppointmentBookingSystem.Application.Services.Implementation;
using AppointmentBookingSystem.Application.Services.Interface;
using AppointmentBookingSystem.Domain.Entities;
using AppointmentBookingSystem.Web.ViewModels;
using Hangfire;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AppointmentBookingSystem.Web.Controllers
{
    [Authorize]
    public class BookingController : Controller
    {
        private readonly IBookingService _bookingService;
        private readonly ISpecialtyService _specialtyService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ISlotService _slotService;
        private readonly IEmailService _emailService;

        public BookingController(IBookingService bookingService, ISpecialtyService specialtyService, UserManager<ApplicationUser> userManager, ISlotService slotService, IEmailService emailService)
        {

            _bookingService = bookingService;
            _specialtyService = specialtyService;
            _userManager = userManager;
            _slotService = slotService;
            _emailService = emailService;
        }


        public async Task<IActionResult> IndexAsync()
        {
            var user = await _userManager.GetUserAsync(User);

            
            if (await _userManager.IsInRoleAsync(user, SD.Role_Admin))
            {
                var booking = _bookingService.GetAllBooking();
                return View(booking);
            }
            else
            {
                var booking = _bookingService.GetAllBookingByCustomer(user.Id);
                return View(booking);
            }
           
        }

        public async Task<IActionResult> CreateAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            IEnumerable<ApplicationUser> customers;

            if (await _userManager.IsInRoleAsync(user, SD.Role_Admin))
            {
                customers = await _userManager.GetUsersInRoleAsync("Customer");
            }
            else
            {
                customers = new List<ApplicationUser> { user };

            }
         
            BookingVM bookingVM = new()
            {
                Specialties = _specialtyService.GetAllSpecialtys().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                
                Customers = customers.Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }).ToList()
            };
            
            return View(bookingVM);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(BookingVM obj)
        {


            bool slotExists = _bookingService.CheckBookingExists(obj.Booking.Id);

            if (ModelState.IsValid && !slotExists)
            {
                
                var slot = _slotService.GetSlotById(obj.Booking.SlotId);
                if (!_bookingService.checkBookingExitByCustomer(obj.Booking))
                {
                    if (_bookingService.getBookingCountOnDate(obj.Booking) <= slot.MaxPatients)
                    {
                     
                        _bookingService.CreateBooking(obj.Booking);
                        TempData["success"] = "The Booking has been created successfully.";
                      
                        obj.Booking.Slot=slot;
                        obj.Booking.Customer = await _userManager.FindByIdAsync(obj.Booking.CustomerId);
                        BackgroundJob.Enqueue(() => _emailService.SendEmailConfirmation(obj.Booking.Customer, obj.Booking));
                       
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        TempData["error"] = "Booking limit for the selected date has been reached.";
                        return RedirectToAction(nameof(Index));
                    }
                }
                else
                {
                    TempData["error"] = "You have already made a booking for this slot.";
                    return RedirectToAction(nameof(Index));
                }
            }

            if (slotExists)
            {
                TempData["error"] = "The Booking already exists.";
            }
            var customers = await _userManager.GetUsersInRoleAsync("Customer");
            obj.Specialties = _specialtyService.GetAllSpecialtys().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            obj.Customers = customers.Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }).ToList();
            return View(obj);
        }
      
        public async Task<IActionResult> DeleteAsync(int bookingId)
        {
            Booking? objFromDb = _bookingService.GetBookingById(bookingId);
            if (objFromDb is not null)
            {
                _bookingService.DeleteBooking(objFromDb.Id);
                TempData["success"] = "The Booking has been cancle successfully.";
                
                BackgroundJob.Enqueue(() => _emailService.SendEmailConfirmation(objFromDb.Customer, objFromDb));
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The booking could not be cancle.";
            return View();
            
        }
  
    }
}

AppointmentBookingSystem/AppointmentBookingSystem.Web/Controllers/DoctorController.cs
using AppointmentBookingSystem.Application.Services.Implementation;
using AppointmentBookingSystem.Application.Services.Interface;
using AppointmentBookingSystem.Domain.Entities;
using AppointmentBookingSystem.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;

namespace AppointmentBookingSystem.Web.Controllers
{
    [Authorize]
    public class DoctorController : Controller
    {
        private readonly IDoctorService _docterService;
        private readonly ISpecialtyService _specialtyService;
        public DoctorController(IDoctorService docterService, ISpecialtyService specialtyService)
        {
            _docterService = docterService;
            _specialtyService = specialtyService;
        }


        public IActionResult Index()
        {
          
            var docters = _docterService.GetAllDoctors();
            return View(docters);
        }

        public IActionResult Create()
        {
            DoctorVM docterVM = new()
            {
                SpecialtyList = _specialtyService.GetAllSpecialtys().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            return View(docterVM);
        }

        [HttpPost]
        public IActionResult Create(DoctorVM obj)
        {


            bool roomNumberExists = _docterService.CheckDoctorExists(obj.Docter.Id);

            if (ModelState.IsValid && !roomNumberExists)
            {
                _docterService.CreateDoctor(obj.Docter);
                TempData["success"] = "The doctor has been created successfully.";
                return RedirectToAction(nameof(Index));
            }

            if (roomNumberExists)
            {
                TempData["error"] = "The doctor already exists.";
            }
            obj.SpecialtyList = _specialtyService.GetAllSpecialtys().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(obj);
        }

        public IActionResult Update(int doctorId)
        {
            DoctorVM doctorVM = new()
            {
                SpecialtyList = _specialtyService.GetAllSpecialtys().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Docter = _docterService.GetDoctorById(doctorId)
            };
            if (doctorVM.Docter == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(doctorVM);
        }


        [HttpPost]
        public IActionResult Update(DoctorVM doctorVM)
        {

            if (ModelState.IsValid)
            {
                _docterService.UpdateDoctor(doctorVM.Docter);
                TempData["success"] = "The docter has been updated successfully.";
                return RedirectToAction(nameof(Index));
            }

            doctorVM.SpecialtyList = _specialtyService.GetAllSpecialtys().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(doctorVM);
        }



        public IActionResult Delete(int doctorId)
        {
            DoctorVM doctorVM = new()
            {
                SpecialtyList = _specialtyService.GetAllSpecialtys().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Docter = _docterService.GetDoctorById(doctorId)
            };
            if (doctorVM.Docter == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(doctorVM);
        }



        [HttpPost]
        public IActionResult Delete(DoctorVM doctorVM)
        {
            Doctor? objFromDb = _docterService.GetDoctorById(doctorVM.Docter.Id);
            if (objFromDb is not null)
            {
                _docterService.DeleteDoctor(objFromDb.Id);
                TempData["success"] = "The docter has been deleted successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The docter could not be deleted.";
            return View();
        }
        [AllowAnonymous]
       
        public IActionResult GetDoctorsBySpecialty(int specialtyId)
        {
            if (specialtyId <= 0)
            {
                return BadRequest(new { message = "Invalid specialtyId." });
            }

            // return Ok(Json(_docterService.GetDoctorBySpecialtyId(specialtyId)));

            var specialty= _docterService.GetDoctorBySpecialtyId(specialtyId).Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return Ok(specialty);
        }
    }
}

AppointmentBookingSystem/AppointmentBookingSystem.Web/Controllers/SlotController.cs
using AppointmentBookingSystem.Application.Services.Interface;
using AppointmentBookingSystem.Domain.Entities;
using AppointmentBookingSystem.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace AppointmentBookingSystem.Web.Controllers
{
    [Authorize]
    public class SlotController : Controller
    {
        private readonly ISlotService _slotService;
        private readonly IDoctorService _docterService;
        
        public SlotController(ISlotService slotService, IDoctorService docterService)
        {

            _slotService = slotService;
            _docterService = docterService;
        }


        public IActionResult Index()
        {
            var slot = _slotService.GetAllSlot();
            return View(slot);
        }

        public IActionResult Create()
        {
            SlotVM slotVM = new()
            {
                DoctorList = _docterService.GetAllDoctors().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            return View(slotVM);
        }

        [HttpPost]
        public IActionResult Create(SlotVM obj)
        {


            bool slotExists = _slotService.CheckSlotExists(obj.Slot.Id);

            if (ModelState.IsValid && !slotExists)
            {
                _slotService.CreateSlot(obj.Slot);
                TempData["success"] = "The Slot has been created successfully.";
                return RedirectToAction(nameof(Index));
            }

            if (slotExists)
            {
                TempData["error"] = "The Slot already exists.";
            }
            obj.DoctorList = _docterService.GetAllDoctors().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(obj);
        }

        public IActionResult Update(int slotId)
        {
            SlotVM slotVM = new()
            {
                DoctorList = _docterService.GetAllDoctors().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Slot = _slotService.GetSlotById(slotId)
            };
            if (slotVM.Slot == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(slotVM);
        }


        [HttpPost]
        public IActionResult Update(SlotVM slotVM)
        {

            if (ModelState.IsValid)
            {
                _slotService.UpdateSlot(slotVM.Slot);
                TempData["success"] = "The Slot has been updated successfully.";
                return RedirectToAction(nameof(Index));
            }

            slotVM.DoctorList = _docterService.GetAllDoctors().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(slotVM);
        }
        public IActionResult Delete(int slotId)
        {
            SlotVM slotVM = new()
            {
                DoctorList = _docterService.GetAllDoctors().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Slot = _slotService.GetSlotById(slotId)
            };
            if (slotVM.Slot == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(slotVM);
        }



        [HttpPost]
        public IActionResult Delete(SlotVM slotVM)
        {
            Slot? objFromDb = _slotService.GetSlotById(slotVM.Slot.Id);
            if (objFromDb is not null)
            {
                _slotService.DeleteSlot(objFromDb.Id);
                TempData["success"] = "The slot has been deleted successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The slot could not be deleted.";
            return View();
        }
       
        public IActionResult GetTimeSlots(int doctorId, string date)
        {
            if (doctorId <= 0)
            {
                return BadRequest(new { message = "Invalid doctorId." });
            }
            var slot= _slotService.GetSlotByDoctorIdAndDays(doctorId, date).Select(u => new SelectListItem
            {
                Text = $"{(new DateTime(2000, 1, 1).Add(u.StartTime)):hh:mm tt} - {(new DateTime(2000, 1, 1).Add(u.EndTime)):hh:mm tt}",
                Value = u.Id.ToString()
            });
            return Ok(slot);

        }
 
        public IActionResult GetAvailableDays(int doctorId)
        {
            var availableDays = _slotService.GetSlotByDoctorId(doctorId)
                                    .Select(s => s.DayOfWeek)
                                    .Distinct()
                                    .ToList();

            // Convert the integer values to day names
            var dayNames = availableDays.Select(day => Enum.GetName(typeof(DayOfWeek), day))
                                        .ToList();

            return Ok(dayNames);

        }
    }
}

AppointmentBookingSystem/AppointmentBookingSystem.Web/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/account.css" asp-append-version="true" />
</head>
<body>

    <div>
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AppointmentBookingSystem/AppointmentBookingSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppointmentBookingSystem</title>
    <link rel="stylesheet" href="~/AppointmentBookingSystem.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css" integrity="sha512-Z/def5z5u2aR89OuzYcxmDJ0Bnd5V1cKqBEbvLOiUNWdg9PQeXVvXLI90SE4QOHGlfLqUnDNVAYyZi8UwUTmWQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/spinner.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width:35px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Booking" asp-action="Index">Manage Bookings</a>
                        </li>

                    </ul>
                    <div class="p-2 border rounded">
                        <div class="form-check form-switch" id="btnSwitch">
                            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
                            <label class="form-check-label" for="flexSwitchCheckDefault">Mode</label>
                        </div>
                    </div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main">
            <div class="loading spinner" style="display:none;"></div>
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            Made with <i class="bi bi-heart-fill"></i> by PKW
        </div>
    </footer>
    @* jquery-ajax-unobtrusive@3.2.6 *@
    <script type="text/javascript">
        document.getElementById('btnSwitch').addEventListener('click', () => {
            if (document.documentElement.getAttribute('data-bs-theme') == 'dark') {
                document.documentElement.setAttribute('data-bs-theme', 'light')
            }
            else {
                document.documentElement.setAttribute('data-bs-theme', 'dark')
            }
        })
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.bundle.min.js" integrity="sha512-sH8JPhKJUeA9PWk3eOcOl8U+lfZTgtBXD41q6cO/slwxGHCxKcW45K4oPCUhHG7NMB4mbKEddVmPuTXtpbCbFA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @*  <script src="~/js/jquery.unobtrusive-ajax.min.js"></script> *@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AppointmentBookingSystem/AppointmentBookingSystem.Web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppointmentBookingSystem</title>
    <link rel="stylesheet" href="~/AppointmentBookingSystem.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css" integrity="sha512-Z/def5z5u2aR89OuzYcxmDJ0Bnd5V1cKqBEbvLOiUNWdg9PQeXVvXLI90SE4QOHGlfLqUnDNVAYyZi8UwUTmWQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/spinner.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width:35px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                         @* <li class="nav-item">  *@
                         @*     <a class="nav-link" asp-controller="Booking" asp-action="Index">Manage Bookings</a>  *@
                         @* </li>  *@
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Specialty" asp-action="Index">
                                <span class="me-2"><i class="bi bi-journal-plus"></i></span>
                                <span>Specialty</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Doctor" asp-action="Index">
                                <span class="me-2"><i class="bi bi-journal-plus"></i></span>
                                <span>Doctor</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Slot" asp-action="Index">
                                <span class="me-2"><i class="bi bi-journal-plus"></i></span>
                                <span>Slot</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Booking" asp-action="Index">
                                <span class="me-2"><i class="bi bi-journal-plus"></i></span>
                                <span>Booking</span>
                            </a>
                        </li>
                    </ul>
                    <div class="p-2 border rounded">
                        <div class="form-check form-switch" id="btnSwitch">
                            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
                            <label class="form-check-label" for="flexSwitchCheckDefault">Mode</label>
                        </div>
                    </div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main">
            <div class="loading spinner" style="display:none;"></div>
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            Made with <i class="bi bi-heart-fill"></i> by PKW
        </div>
    </footer>
    @* jquery-ajax-unobtrusive@3.2.6 *@
    <script type="text/javascript">
        document.getElementById('btnSwitch').addEventListener('click', () => {
            if (document.documentElement.getAttribute('data-bs-theme') == 'dark') {
                document.documentElement.setAttribute('data-bs-theme', 'light')
            }
            else {
                document.documentElement.setAttribute('data-bs-theme', 'dark')
            }
        })
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.bundle.min.js" integrity="sha512-sH8JPhKJUeA9PWk3eOcOl8U+lfZTgtBXD41q6cO/slwxGHCxKcW45K4oPCUhHG7NMB4mbKEddVmPuTXtpbCbFA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    @*  <script src="~/js/jquery.unobtrusive-ajax.min.js"></script> *@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AppointmentBookingSystem/AppointmentBookingSystem.Web/Views/Shared/_LoginPartialAdmin.cshtml
@using AppointmentBookingSystem.Domain.Entities
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<ul class="navbar-nav  d-none d-md-flex nav-login">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
        data-bs-toggle="dropdown" aria-expanded="false">
            Hello @UserManager.GetUserName(User)
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="nav-link text-center" asp-controller="Account" asp-action="Logout">Logout</a>
        </ul>
    </li>
</ul>

AppointmentBookingSystem/AppointmentBookingSystem.Web/Views/Shared/_Notification.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}