AppointmentBookingSystem/AppointmentBookingSystem.Web/Controllers/SpecialtyController.cs
using AppointmentBookingSystem.Application.Services.Interface;
using AppointmentBookingSystem.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AppointmentBookingSystem.Web.Controllers
{
    [Authorize]
    public class SpecialtyController : Controller
    {
        private readonly ISpecialtyService _specialtyService;

        public SpecialtyController(ISpecialtyService specialtyService)
        {
            _specialtyService = specialtyService;
        }


        public IActionResult Index()
        {
            var specialty = _specialtyService.GetAllSpecialtys();
            return View(specialty);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Specialty obj)
        {

            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("name", "The description cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {

                _specialtyService.CreateSpecialty(obj);
                TempData["success"] = "The specialty has been created successfully.";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Update(int specialtyId)
        {
            Specialty? obj = _specialtyService.GetSpecialtyById(specialtyId);
            if (obj == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Update(Specialty obj)
        {
            if (ModelState.IsValid && obj.Id > 0)
            {

                _specialtyService.UpdateSpecialty(obj);
                TempData["success"] = "The specialty has been updated successfully.";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Delete(int specialtyId)
        {
            Specialty? obj = _specialtyService.GetSpecialtyById(specialtyId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }


        [HttpPost]
        public IActionResult Delete(Specialty obj)
        {
            bool deleted = _specialtyService.DeleteSpecialty(obj.Id);
            if (deleted)
            {
                TempData["success"] = "The specialty has been deleted successfully.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = "Failed to delete the specialty.";
            }
            return View();
        }
    }
}

AppointmentBookingSystem/AppointmentBookingSystem.Web/Views/Specialty/Create.cshtml
@model AppointmentBookingSystem.Domain.Entities.Specialty


<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Specialty</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" >
            <div class="p-3">
                @* <div asp-validation-summary="All"></div>  *@
                <div class="form-floating py-1 col-12">
                    <input asp-for="Name" class="form-control border shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Description" class="form-control border shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Code" class="form-control border shadow" />
                    <label asp-for="Code" class="ms-2"></label>
                    <span asp-validation-for="Code" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Specialty" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

AppointmentBookingSystem/AppointmentBookingSystem.Web/Views/Specialty/Delete.cshtml
@model AppointmentBookingSystem.Domain.Entities.Specialty

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Specialty</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="Id" hidden />
            <div class="col-10">
            <div class="p-3">
                @* <div asp-validation-summary="All"></div> *@
                <div class="form-floating py-1 col-12">
                    <input asp-for="Name" disabled class="form-control border shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Description" disabled class="form-control border shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                </div>
                <div class="form-floating py-1 col-12">
                        <input asp-for="Code" disabled class="form-control border shadow" />
                        <label asp-for="Code" class="ms-2"></label>
                </div>
                
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger w-100">
                            <i class="bi bi-trash-fill"></i> Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                            <a asp-controller="Specialty" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
            </div>
           
        </form>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

AppointmentBookingSystem/AppointmentBookingSystem.Web/Views/Specialty/Index.cshtml
@model IEnumerable<AppointmentBookingSystem.Domain.Entities.Specialty>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Specialty List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Specialty" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Create New Specialty
                </a>
            </div>
        </div>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>Description</th>
                    <th>Code</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Name</td>
                        <td>@obj.Description</td>
                        <td>@obj.Code</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Specialty" asp-action="Update" asp-route-specialtyId="@obj.Id"
                                   class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="Specialty" asp-action="Delete" asp-route-specialtyId="@obj.Id"
                                   class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

AppointmentBookingSystem/AppointmentBookingSystem.Web/Views/Specialty/Update.cshtml
@model AppointmentBookingSystem.Domain.Entities.Specialty

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Specialty</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="Id" hidden />
            <div class="col-10">
                <div class="p-3">
                    @* <div asp-validation-summary="All"></div> *@
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Name" class="form-control border shadow" />
                        <label asp-for="Name" class="ms-2"></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Description" class="form-control border shadow" />
                        <label asp-for="Description" class="ms-2"></label>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Code" class="form-control border shadow" />
                        <label asp-for="Code" class="ms-2"></label>
                        <span asp-validation-for="Code" class="text-danger"></span>
                    </div>
                  
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success w-100">
                                <i class="bi bi-check-circle"></i> Update
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="Specialty" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle"></i> Cancel
                            </a>
                        </div>
                    </div>
                </div>
            </div>
           
            
        </form>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}